---
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0de53d8956e8dcf80
      # ami-a4c7edb2jkahsdkja
      InstanceType: t2.micro
